### ISSUE TITLE
net_exporter cant work

### ISSUE THREAD

**Issue by yulidai** [certusone/chain_exporter#2]
after reading the code, it seems the error come from this code
`tClient := client.NewHTTP(item, "/websocket")`

the error of it is(address is not real)
```
error parsing netData for gaia-rpc-gaia-testnet.apps..nip.io:26657: NetInfo: Post https://gaia-rpc-gaia-testnet.apps..nip.io:26657: EOF
```

Any help will be greatly appreciated :)

**Comment by yulidai** [comment]
sorry, the error comes from `netInfo, err := client.NetInfo()`

**Comment by hendrikhofstadt** [comment]
@yulidai Thanks for reporting this issue.

Is your URL `gaia-rpc-gaia-testnet.apps..nip.io` or did you censor the IP? Because the address you sent is invalid.

**Comment by yulidai** [comment]
yes, It's not real IP.

we used https without certificate（so the browser will remind not safe, but can access）
maybe it caused by https?

**Comment by leoluk** [comment]
You deployed this with https://github.com/certusone/testnet_deploy, correct?

Please test whether the SSL connection works:

    openssl s_client -connect gaia-rpc-gaia-testnet.apps..nip.io:26657

I would suspect that the gaia node providing the RPC service is not running correctly, hence the EOF (OpenShift load balancer can't reach the backend). Please provide the output of:

    oc get pod

**Comment by yulidai** [comment]
@leoluk thank you for replying
```
openssl s_client -connect gaia-rpc-gaia-testnet.apps.nip.io:26657
CONNECTED(00000005)
```
tips: url is not real

the result of `oc get pod` will provided later

**Comment by leoluk** [comment]
Is that all it prints, or does it show key exchange?

**Comment by yulidai** [comment]
@leoluk here is the result of `oc get pod`

```
[root@cosmos-test ~]# oc get pods
NAME                       READY     STATUS             RESTARTS   AGE
gaia-alerter-1-deploy      0/1       Error              0          12d
gaia-alerter-4-spx44       1/1       Running            0          12d
gaia-ansible-1-build       0/1       Completed          0          12d
gaia-ansible-2-build       0/1       Completed          0          12d
gaia-ansible-3-build       0/1       Completed          0          12d
gaia-deploy-8qwtb          0/1       Completed          0          12d
gaia-exporter-1-build      0/1       Completed          0          12d
gaia-exporter-1-deploy     0/1       Error              0          12d
gaia-exporter-2-build      0/1       Completed          0          12d
gaia-exporter-4-sds6f      1/1       Running            0          12d
gaia-lcd-3-674xp           1/1       Running            0          12d
gaia-lcd-4-deploy          0/1       Error              0          12d
gaia-node0                 1/1       Running            0          12d
gaia-node1                 1/1       Running            0          12d
gaia-node2                 0/1       Evicted            0          12d
gaia-node3                 1/1       Running            0          12d
gaiad-1-build              0/1       Completed          0          12d
gaiad-2-build              0/1       Completed          0          12d
golang-s2i-1-build         0/1       Completed          0          12d
grafana-6848d4cd74-fxqsp   2/2       Running            0          12d
kafka-1-deploy             0/1       Error              0          12d
kafka-zk-1-gszhr           0/1       CrashLoopBackOff   3407       12d
net-exporter-1-deploy      0/1       Error              0          12d
net-exporter-4-5ph8z       1/1       Running            0          12d
postgres-chain-1-ssw7d     1/1       Running            0          12d
prom-0                     4/4       Running            0          12d
```

**Comment by yulidai** [comment]
i thought it is all print, but try again and wait 1 minute after you asked, more info was printed:
```
openssl s_client -connect gaia-rpc-gaia-testnet.apps.nip.io:26657
CONNECTED(00000005)
4404541036:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.200.4/libressl-2.6/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Start Time: 1543670206
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

it seems caused by https without certicate?

**Comment by leoluk** [comment]
That's fine, it means the OpenShift router (which terminates TLS) works. I would assume that the gaia-rpc service in OpenShift is not running correctly, resulting in a stream EOF.

**Comment by yulidai** [comment]
the result of visiting gaia-rpc-gaia-testnet.apps.nip.io（:80) by chrome, will show list like:
```
Available endpoints:
//gaia-rpc-gaia-testnet.apps.nip.io/abci_info
//gaia-rpc-gaia-testnet.apps.nip.io/consensus_state
//gaia-rpc-gaia-testnet.apps.nip.io/dump_consensus_state
//gaia-rpc-gaia-testnet.apps.nip.io/genesis
//gaia-rpc-gaia-testnet.apps.nip.io/health
//gaia-rpc-gaia-testnet.apps.nip.io/net_info
//gaia-rpc-gaia-testnet.apps.nip.io/num_unconfirmed_txs
//gaia-rpc-gaia-testnet.apps.nip.io/status

Endpoints that require arguments:
//gaia-rpc-gaia-testnet.apps.nip.io/abci_query?path=_&data=_&height=_&prove=_
//gaia-rpc-gaia-testnet.apps.nip.io/block?height=_
//gaia-rpc-gaia-testnet.apps.nip.io/block_results?height=_
//gaia-rpc-gaia-testnet.apps.nip.io/blockchain?minHeight=_&maxHeight=_
//gaia-rpc-gaia-testnet.apps.nip.io/broadcast_tx_async?tx=_
//gaia-rpc-gaia-testnet.apps.nip.io/broadcast_tx_commit?tx=_
//gaia-rpc-gaia-testnet.apps.nip.io/broadcast_tx_sync?tx=_
//gaia-rpc-gaia-testnet.apps.nip.io/commit?height=_
//gaia-rpc-gaia-testnet.apps.nip.io/consensus_params?height=_
//gaia-rpc-gaia-testnet.apps.nip.io/subscribe?query=_
//gaia-rpc-gaia-testnet.apps.nip.io/tx?hash=_&prove=_
//gaia-rpc-gaia-testnet.apps.nip.io/tx_search?query=_&prove=_&page=_&per_page=_
//gaia-rpc-gaia-testnet.apps.nip.io/unconfirmed_txs?limit=_
//gaia-rpc-gaia-testnet.apps.nip.io/unsubscribe?query=_
//gaia-rpc-gaia-testnet.apps.nip.io/unsubscribe_all?
//gaia-rpc-gaia-testnet.apps.nip.io/validators?height=_
```
all will get result by clicking `Available endpoints` links

what should i do for fixing the problem?

**Comment by yulidai** [comment]
@leoluk hi, do you have any other ideas?  thank you  :)

**Comment by yulidai** [comment]
@leoluk very sorry for disturbing you again, im newbie for this...
can you teach me how to check gaia-rpc service in OpenShift is running correctly or not?

**Comment by hendrikhofstadt** [comment]
@yulidai Which version of tendermint / cosmos are you running ?

**Comment by yulidai** [comment]
@Slamper both 0.26.1 and 0.26.4 have this problem

the version is displayed in the gaia-rpc-gaia-testnet.apps.nip.io:26657/status

**Comment by yulidai** [comment]
Very very sorry about that, it's because i used proxy for speeding network...

**Comment by hendrikhofstadt** [comment]
@yulidai
Oh no problem at all.

Does it work now ?

**Comment by yulidai** [comment]
@Slamper

**Comment by yulidai** [comment]
@Slamper no, still has problem

when visit my node, get this response:
`error parsing netData for **.**.**.**:26657: NetInfo: Error unmarshalling rpc response result: json: cannot unmarshal object into Go value of type []json.RawMessage`

As a contrast, if i visit http://gaia-seed1.interblock.io:26657 will get correct response:
`parsed netData for gaia-seed1.interblock.io:26657`
but sometime also get
`error parsing netData for gaia-seed1.interblock.io:26657: NetInfo: Error unmarshalling rpc response result: json: cannot unmarshal object into Go value of type []json.RawMessage`

both tendermint's version is 0.26.4, very strange

**Comment by yulidai** [comment]
it seems the error come from `github.com⁩/⁨tendermint⁩/⁨tendermint⁩/⁨rpc⁩/⁨lib⁩/⁨client⁩/http_client.go`
detail showed below:
```
func unmarshalResponseBytes(cdc *amino.Codec, responseBytes []byte, result interface{}) (interface{}, error) {
	// Read response.  If rpc/core/types is imported, the result will unmarshal
	// into the correct type.
	// log.Notice("response", "response", string(responseBytes))
	var err error
	response := &types.RPCResponse{}
	err = json.Unmarshal(responseBytes, response)
	if err != nil {
		return nil, errors.Errorf("Error unmarshalling rpc response: %v", err)
	}
	if response.Error != nil {
		return nil, errors.Errorf("Response error: %v", response.Error)
	}
	// Unmarshal the RawMessage into the result.
	err = cdc.UnmarshalJSON(response.Result, result)
	if err != nil {
		fmt.Printf("Failed: %v", result) // ***Add by Me***
		return nil, errors.Errorf("Error unmarshalling rpc response result: %v", err)
	}

	fmt.Printf("Success: %v", result) // ***Add by Me***
	return result, nil
}
```

i print the result either success or not, will get:

**visit my node** 
`Failed: &{true [Listener(@tcp://**.**.**.**:26656)] 39 []}`

**visit `http://gaia-seed1.interblock.io:26657`**
 `Success: &{true [Listener(@)] 0 []}`

seems a little difference but i dont know why  :(

**Comment by yulidai** [comment]
@Slamper hi, can you test net_exporter/main.go by using `http://118.31.0.119:26657`, same problem with mine

so i think `http://gaia-seed1.interblock.io:26657` is success just because its peers' number is zero

**Comment by hendrikhofstadt** [comment]
I think that the problem is the outdated version of the tendermint dependency. I will check it and get back to you

**Comment by yulidai** [comment]
thank you!

**Comment by hendrikhofstadt** [comment]
@yulidai could you please pull and build the code again and try it now ?

**Comment by yulidai** [comment]
yes! wait a moment

**Comment by yulidai** [comment]
@Slamper thanks a lot, it works fine!

net_exporter is ok, i will check chain_exporter later  :P

**Comment by hendrikhofstadt** [comment]
@yulidai Awesome. We have rewritten the current chain_exporter and will soon release it but feel free to play with this version.
